### ISSUE TITLE
medigun icon has missing texture in casual

### ISSUE THREAD

**Issue by TechnoSL** [Vexcenot/Middle-Mann#14]
might be a preloading issue? gives the same error as #2 even though the file is there, need to check further

also the ammo works just fine, but not medic???

**Comment by Renzum** [comment]
The Übercharge icon works fin on a community server, which leads me to believe it might be an sv_pure issue.

**Comment by Renzum** [comment]
Yup can confirm. I set sv_pure 1 in the main menu and loaded itemtest. The icon does not work. But loading up itemtest with sv_pure 0 loads the icon just fine.

**Comment by TechnoSL** [comment]
> Yup can confirm. I set sv_pure 1 in the main menu and loaded itemtest. The icon does not work. But loading up itemtest with sv_pure 0 loads the icon just fine.

noted, will probably have to preload but for now i will be disabling the medic icon until further testing

**Comment by Renzum** [comment]
If by preloading you mean loading up an sv_pure 0 server on stratup, for example itemtest, that doesn't work either. I have a script setup in my autoexec to do just that for my custom animations. The uber icon doesn't work still.

**Comment by Renzum** [comment]
I'm not a hud maker myself, so I can't suggest anything drastic either. The only two options I can think of is either to disable the icon completely, or use the default tf2 one.

**Comment by Renzum** [comment]
I disabled the Icon in my PR #23.
