### ISSUE TITLE
Fonts do not work on Linux

### ISSUE THREAD

**Issue by Nelson340** [Vexcenot/Middle-Mann#4]
When using this HUD on Linux, instead of the usual TF2-style fonts I see plain-looking fonts most of the time.
![20230714172534_1](https://github.com/Vexcenot/Middle-Mann/assets/22733426/36ab6247-9e2c-4470-b443-597f0cd40adb)
![20230714173308_1](https://github.com/Vexcenot/Middle-Mann/assets/22733426/1013c0fd-49a9-4d85-bd79-7f06aa39b016)

**Comment by halamix2** [comment]
You need to manually install system or user-wide TF2 *.ttf fonts from the `~/.steam//home/halamix2/.steam/steam/steamapps/common/Team Fortress 2/tf/resource/` directory

**Comment by TechnoSL** [comment]
thanks for reporting.

unfortunately as i dont have a linux system to test the hud on it will be hard to fix.

for now the fix suggested above works fine, probably

**Comment by TechnoSL** [comment]
reopening as this apparently isn't fixed yet from a report i got yesterday, will keep looking

**Comment by TechnoSL** [comment]
ok no i give up installing fonts is easier thanks for the report anyway
